// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YTTrending.Infrastructure.Persistence;

#nullable disable

namespace YTTrending.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YTTrendingDbContext))]
    partial class YTTrendingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YTTrending.Domain.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("youtube_channel_id");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("YoutubeChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_youtube_channel_id");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.SavedIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_ideas");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_ideas_video_id");

                    b.ToTable("saved_ideas", (string)null);
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.TrendingScore", b =>
                {
                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("video_id");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<decimal>("VelocityNorm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("velocity_norm");

                    b.Property<decimal>("VelocityPerHour")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("velocity_per_hour");

                    b.Property<decimal>("ViewGrowthNorm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("view_growth_norm");

                    b.Property<decimal>("ViewGrowthPct")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("view_growth_pct");

                    b.HasKey("VideoId")
                        .HasName("pk_trending_scores");

                    b.ToTable("trending_scores", (string)null);
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<long>("LatestComments")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_comments");

                    b.Property<long>("LatestLikes")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_likes");

                    b.Property<long>("LatestViews")
                        .HasColumnType("bigint")
                        .HasColumnName("latest_views");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("youtube_video_id");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_videos_channel_id");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_youtube_video_id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.VideoMetricSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Comments")
                        .HasColumnType("bigint")
                        .HasColumnName("comments");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint")
                        .HasColumnName("likes");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<int>("VideoId")
                        .HasColumnType("integer")
                        .HasColumnName("video_id");

                    b.Property<long>("Views")
                        .HasColumnType("bigint")
                        .HasColumnName("views");

                    b.HasKey("Id")
                        .HasName("pk_video_metric_snapshots");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_video_metric_snapshots_video_id");

                    b.ToTable("video_metric_snapshots", (string)null);
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.SavedIdea", b =>
                {
                    b.HasOne("YTTrending.Domain.Entities.Video", null)
                        .WithOne("SavedIdea")
                        .HasForeignKey("YTTrending.Domain.Entities.SavedIdea", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_ideas_videos_video_id");
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.TrendingScore", b =>
                {
                    b.HasOne("YTTrending.Domain.Entities.Video", null)
                        .WithOne("TrendingScore")
                        .HasForeignKey("YTTrending.Domain.Entities.TrendingScore", "VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trending_scores_videos_video_id");
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.Video", b =>
                {
                    b.HasOne("YTTrending.Domain.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_videos_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.VideoMetricSnapshot", b =>
                {
                    b.HasOne("YTTrending.Domain.Entities.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_video_metric_snapshots_videos_video_id");
                });

            modelBuilder.Entity("YTTrending.Domain.Entities.Video", b =>
                {
                    b.Navigation("SavedIdea");

                    b.Navigation("TrendingScore");
                });
#pragma warning restore 612, 618
        }
    }
}
